In [1]:
import numpy as np
import os

def create_test_data(binary_filename, shape_filename, depth, rows, cols):
    # Create a small predefined 3D array
    data = np.arange(depth * rows * cols).reshape((depth, rows, cols)).astype(np.float32)
    
    # Print the shape of the array to verify it's 3D
    print(f"Array shape: {data.shape}")
    
    # Print the array
    print("Array data:")
    print(data)

    # Ensure the directory exists
    os.makedirs(os.path.dirname(binary_filename), exist_ok=True)

    # Save the 3D array to a binary file
    data.tofile(binary_filename)

    # Save the shape information to a text file
    with open(shape_filename, 'w') as f:
        f.write(f"{depth} {rows} {cols}\n")

if __name__ == "__main__":
    binary_filename = "../../Final/data/test/test.bin"
    shape_filename = "../../Final/data/test/test_shape.txt"
    depth = 3
    rows = 4
    cols = 4

    create_test_data(binary_filename, shape_filename, depth, rows, cols)
    print(f"Test data created: {binary_filename} and {shape_filename}")

Array shape: (3, 4, 4)
Array data:
[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]
  [12. 13. 14. 15.]]

 [[16. 17. 18. 19.]
  [20. 21. 22. 23.]
  [24. 25. 26. 27.]
  [28. 29. 30. 31.]]

 [[32. 33. 34. 35.]
  [36. 37. 38. 39.]
  [40. 41. 42. 43.]
  [44. 45. 46. 47.]]]
Test data created: ../../Final/data/test/test.bin and ../../Final/data/test/test_shape.txt
